### ISSUE TITLE
关于”怎么解决 nixos-rebuild 过程中下载失败?“中设置HTTP_PROXY的问题

### ISSUE THREAD

**Issue by dbsxdbsx** [nixos-cn/NixOS-FAQ#12]
参考：https://github.com/nixos-cn/NixOS-FAQ/blob/main/answers/how-to-mannually-download-file-while-nixos-rebuild.md
我本来用的clash。即通过一个订阅url，会反馈很多代理服务器。但问题时这些个代理服务器的用户名和密码我不知道，若只填代理服务器的ip和port，设置后的`curl ...` 会提示服务器没有反馈。   在不装应用的情况下，在纯终端中应该怎么做呢？

**Comment by Ninlives** [comment]
issue与NixOS及Nix本身无关，建议前往Clash社区提问。
