### ISSUE TITLE
为什么国内的二进制缓存镜像不全？

### ISSUE THREAD

**Issue by sunn4room** [nixos-cn/NixOS-FAQ#14]
我使用的是flake的配置方案，nixpkgs用的tsinghua的git镜像，substituters用的也是tsinghua的store镜像，配置都一个月没更新了，结果重新部署的时候，还是有个别二进制包的下载走的是官方的缓存，即`https://cache.nixos.org/`，而且下载速度很慢。请问这是为什么？既然是镜像，为什么官方缓存有的，镜像里却没有？我知道同步是有时限的，但等到第二天再部署，还是同样的问题。

**Comment by Vonfry** [comment]
这个你要找清华等镜像站，而不是来这里发 issue。
其次，像交大这种镜像好像是有人请求才会去拉，然后过一段时间清理。清华这种好像是只有 stable 的一部分。毕竟全部存储的情况压力是很大的。cache.nixos.org 上是有所有 commit 的所有可二次分发的二进制包的（历史也是不清的），自然很多情况会走这里。
